#!/bin/bash
if [ "$INET_ROOT" = "" ]; then
  echo "INET version not selected. Please run 'source setenv' in the root folder of the INET installation you want to use."
  exit 1
fi

PATH=$INET_ROOT/src:$PATH

opp_run -l ../src/flora -n .:../src:$INET_ROOT/src "$@"
